version: '3.9'

services:
  postgres:
    image: postgres:16.2-alpine3.19
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=cbeaurai
      - POSTGRES_DB=piscineds
