version: '3.9'

services:
  postgres:
    image: postgres:16.2-alpine3.19
    ports:
      - 5432:5432
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=cbeaurai
      - POSTGRES_DB=piscineds
  pgadmin:
    image: dpage/pgadmin4:8.5
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=cbeaurai@student.42.fr
      - PGADMIN_DEFAULT_PASSWORD=mysecretpassword
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
